// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO jobhub.companies (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at, status, is_verified
`

func (q *Queries) CreateCompany(ctx context.Context, name string) (JobhubCompany, error) {
	row := q.db.QueryRow(ctx, createCompany, name)
	var i JobhubCompany
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.IsVerified,
	)
	return i, err
}

const createCompanyMembership = `-- name: CreateCompanyMembership :one
INSERT INTO jobhub.company_memberships (company_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, company_id, user_id, role, created_at, updated_at
`

type CreateCompanyMembershipParams struct {
	CompanyID pgtype.UUID
	UserID    pgtype.UUID
	Role      string
}

func (q *Queries) CreateCompanyMembership(ctx context.Context, arg CreateCompanyMembershipParams) (JobhubCompanyMembership, error) {
	row := q.db.QueryRow(ctx, createCompanyMembership, arg.CompanyID, arg.UserID, arg.Role)
	var i JobhubCompanyMembership
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO jobhub.sessions (user_id, token_hash, csrf_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, csrf_hash, expires_at, revoked_at, created_at
`

type CreateSessionParams struct {
	UserID    pgtype.UUID
	TokenHash []byte
	CsrfHash  []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (JobhubSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.CsrfHash,
		arg.ExpiresAt,
	)
	var i JobhubSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CsrfHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO jobhub.users (full_name, email, normalized_email, password_hash, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, full_name, email, normalized_email, password_hash, role, status, created_at, updated_at
`

type CreateUserParams struct {
	FullName        string
	Email           string
	NormalizedEmail string
	PasswordHash    string
	Role            string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (JobhubUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FullName,
		arg.Email,
		arg.NormalizedEmail,
		arg.PasswordHash,
		arg.Role,
	)
	var i JobhubUser
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.NormalizedEmail,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM jobhub.sessions
WHERE expires_at < now() OR revoked_at IS NOT NULL
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const getCompanyForUser = `-- name: GetCompanyForUser :one
SELECT c.id, c.name, c.created_at, c.updated_at, c.status, c.is_verified
FROM jobhub.companies c
JOIN jobhub.company_memberships cm ON cm.company_id = c.id
WHERE cm.user_id = $1
ORDER BY cm.created_at ASC
LIMIT 1
`

func (q *Queries) GetCompanyForUser(ctx context.Context, userID pgtype.UUID) (JobhubCompany, error) {
	row := q.db.QueryRow(ctx, getCompanyForUser, userID)
	var i JobhubCompany
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.IsVerified,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT s.id, s.user_id, s.token_hash, s.csrf_hash, s.expires_at, s.revoked_at, s.created_at, u.id, u.full_name, u.email, u.normalized_email, u.password_hash, u.role, u.status, u.created_at, u.updated_at
FROM jobhub.sessions s
JOIN jobhub.users u ON u.id = s.user_id
WHERE s.token_hash = $1
`

type GetSessionByTokenHashRow struct {
	JobhubSession JobhubSession
	JobhubUser    JobhubUser
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.JobhubSession.ID,
		&i.JobhubSession.UserID,
		&i.JobhubSession.TokenHash,
		&i.JobhubSession.CsrfHash,
		&i.JobhubSession.ExpiresAt,
		&i.JobhubSession.RevokedAt,
		&i.JobhubSession.CreatedAt,
		&i.JobhubUser.ID,
		&i.JobhubUser.FullName,
		&i.JobhubUser.Email,
		&i.JobhubUser.NormalizedEmail,
		&i.JobhubUser.PasswordHash,
		&i.JobhubUser.Role,
		&i.JobhubUser.Status,
		&i.JobhubUser.CreatedAt,
		&i.JobhubUser.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, full_name, email, normalized_email, password_hash, role, status, created_at, updated_at FROM jobhub.users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (JobhubUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i JobhubUser
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.NormalizedEmail,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByNormalizedEmail = `-- name: GetUserByNormalizedEmail :one
SELECT id, full_name, email, normalized_email, password_hash, role, status, created_at, updated_at FROM jobhub.users
WHERE normalized_email = $1
`

func (q *Queries) GetUserByNormalizedEmail(ctx context.Context, normalizedEmail string) (JobhubUser, error) {
	row := q.db.QueryRow(ctx, getUserByNormalizedEmail, normalizedEmail)
	var i JobhubUser
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.NormalizedEmail,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE jobhub.sessions
SET revoked_at = COALESCE(revoked_at, now())
WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}
