// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: health.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const databaseTime = `-- name: DatabaseTime :one
SELECT CURRENT_TIMESTAMP::timestamptz AS database_time
`

func (q *Queries) DatabaseTime(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, databaseTime)
	var database_time pgtype.Timestamptz
	err := row.Scan(&database_time)
	return database_time, err
}
