// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireSourceIngestionLock = `-- name: AcquireSourceIngestionLock :exec
SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
`

func (q *Queries) AcquireSourceIngestionLock(ctx context.Context, source string) error {
	_, err := q.db.Exec(ctx, acquireSourceIngestionLock, source)
	return err
}

const completeIngestionRun = `-- name: CompleteIngestionRun :exec
UPDATE jobhub.ingestion_runs
SET status = 'succeeded',
    request_count = $1,
    fetched_count = $2,
    normalized_count = $3,
    inserted_count = $4,
    updated_count = $5,
    skipped_count = $6,
    finished_at = now()
WHERE id = $7 AND status = 'running'
`

type CompleteIngestionRunParams struct {
	RequestCount    int32
	FetchedCount    int32
	NormalizedCount int32
	InsertedCount   int32
	UpdatedCount    int32
	SkippedCount    int32
	ID              pgtype.UUID
}

func (q *Queries) CompleteIngestionRun(ctx context.Context, arg CompleteIngestionRunParams) error {
	_, err := q.db.Exec(ctx, completeIngestionRun,
		arg.RequestCount,
		arg.FetchedCount,
		arg.NormalizedCount,
		arg.InsertedCount,
		arg.UpdatedCount,
		arg.SkippedCount,
		arg.ID,
	)
	return err
}

const countPublicJobs = `-- name: CountPublicJobs :one
SELECT count(*)
FROM jobhub.jobs j
JOIN jobhub.job_sources s ON s.source = j.source
WHERE s.enabled
  AND (NOT $1::boolean OR s.production_permissions_confirmed)
  AND j.source_status IN ('unknown', 'active')
  AND j.fresh_until > now()
  AND ($2::text IS NULL OR j.title ILIKE '%' || $2 || '%' OR j.company_name_raw ILIKE '%' || $2 || '%')
  AND ($3::text IS NULL OR j.location_raw ILIKE '%' || $3 || '%')
`

type CountPublicJobsParams struct {
	RequireProductionPermissions bool
	Query                        pgtype.Text
	Location                     pgtype.Text
}

func (q *Queries) CountPublicJobs(ctx context.Context, arg CountPublicJobsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicJobs, arg.RequireProductionPermissions, arg.Query, arg.Location)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIngestionRun = `-- name: CreateIngestionRun :one
INSERT INTO jobhub.ingestion_runs (source, search_count)
VALUES ($1, $2)
RETURNING id
`

type CreateIngestionRunParams struct {
	Source      string
	SearchCount int32
}

func (q *Queries) CreateIngestionRun(ctx context.Context, arg CreateIngestionRunParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createIngestionRun, arg.Source, arg.SearchCount)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const failIngestionRun = `-- name: FailIngestionRun :exec
UPDATE jobhub.ingestion_runs
SET status = 'failed',
    request_count = $1,
    fetched_count = $2,
    normalized_count = $3,
    error_code = $4,
    error_message = $5,
    finished_at = now()
WHERE id = $6 AND status = 'running'
`

type FailIngestionRunParams struct {
	RequestCount    int32
	FetchedCount    int32
	NormalizedCount int32
	ErrorCode       pgtype.Text
	ErrorMessage    pgtype.Text
	ID              pgtype.UUID
}

func (q *Queries) FailIngestionRun(ctx context.Context, arg FailIngestionRunParams) error {
	_, err := q.db.Exec(ctx, failIngestionRun,
		arg.RequestCount,
		arg.FetchedCount,
		arg.NormalizedCount,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}

const getPublicJob = `-- name: GetPublicJob :one
SELECT j.id, j.source, j.external_id, j.source_url, j.upstream_source_name, j.company_id, j.company_source_id, j.company_name_raw, j.title, j.location_raw, j.description, j.description_kind, j.employment_type_raw, j.salary_raw, j.salary_min, j.salary_max, j.salary_currency, j.salary_period, j.salary_gross, j.salary_is_estimated, j.application_method, j.apply_url, j.source_status, j.publication_status, j.first_seen_at, j.last_seen_at, j.last_synced_at, j.fresh_until, j.external_created_at, j.external_published_at, j.external_updated_at, j.external_updated_raw, j.external_expires_at, j.external_archived_at, j.created_at, j.updated_at
FROM jobhub.jobs j
JOIN jobhub.job_sources s ON s.source = j.source
WHERE j.id = $1
  AND s.enabled
  AND (NOT $2::boolean OR s.production_permissions_confirmed)
  AND j.source_status IN ('unknown', 'active')
  AND j.fresh_until > now()
`

type GetPublicJobParams struct {
	ID                           pgtype.UUID
	RequireProductionPermissions bool
}

func (q *Queries) GetPublicJob(ctx context.Context, arg GetPublicJobParams) (JobhubJob, error) {
	row := q.db.QueryRow(ctx, getPublicJob, arg.ID, arg.RequireProductionPermissions)
	var i JobhubJob
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.SourceUrl,
		&i.UpstreamSourceName,
		&i.CompanyID,
		&i.CompanySourceID,
		&i.CompanyNameRaw,
		&i.Title,
		&i.LocationRaw,
		&i.Description,
		&i.DescriptionKind,
		&i.EmploymentTypeRaw,
		&i.SalaryRaw,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.SalaryPeriod,
		&i.SalaryGross,
		&i.SalaryIsEstimated,
		&i.ApplicationMethod,
		&i.ApplyUrl,
		&i.SourceStatus,
		&i.PublicationStatus,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.LastSyncedAt,
		&i.FreshUntil,
		&i.ExternalCreatedAt,
		&i.ExternalPublishedAt,
		&i.ExternalUpdatedAt,
		&i.ExternalUpdatedRaw,
		&i.ExternalExpiresAt,
		&i.ExternalArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const importedJobExists = `-- name: ImportedJobExists :one
SELECT EXISTS (
    SELECT 1 FROM jobhub.jobs
    WHERE source = $1 AND external_id = $2
)
`

type ImportedJobExistsParams struct {
	Source     string
	ExternalID pgtype.Text
}

func (q *Queries) ImportedJobExists(ctx context.Context, arg ImportedJobExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, importedJobExists, arg.Source, arg.ExternalID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listPublicJobs = `-- name: ListPublicJobs :many
SELECT j.id, j.source, j.external_id, j.source_url, j.upstream_source_name, j.company_id, j.company_source_id, j.company_name_raw, j.title, j.location_raw, j.description, j.description_kind, j.employment_type_raw, j.salary_raw, j.salary_min, j.salary_max, j.salary_currency, j.salary_period, j.salary_gross, j.salary_is_estimated, j.application_method, j.apply_url, j.source_status, j.publication_status, j.first_seen_at, j.last_seen_at, j.last_synced_at, j.fresh_until, j.external_created_at, j.external_published_at, j.external_updated_at, j.external_updated_raw, j.external_expires_at, j.external_archived_at, j.created_at, j.updated_at
FROM jobhub.jobs j
JOIN jobhub.job_sources s ON s.source = j.source
WHERE s.enabled
  AND (NOT $1::boolean OR s.production_permissions_confirmed)
  AND j.source_status IN ('unknown', 'active')
  AND j.fresh_until > now()
  AND ($2::text IS NULL OR j.title ILIKE '%' || $2 || '%' OR j.company_name_raw ILIKE '%' || $2 || '%')
  AND ($3::text IS NULL OR j.location_raw ILIKE '%' || $3 || '%')
ORDER BY
    CASE WHEN $4::text = 'oldest' THEN COALESCE(j.external_published_at, j.first_seen_at) END ASC,
    CASE WHEN $4::text <> 'oldest' THEN COALESCE(j.external_published_at, j.first_seen_at) END DESC,
    j.id DESC
LIMIT $6 OFFSET $5
`

type ListPublicJobsParams struct {
	RequireProductionPermissions bool
	Query                        pgtype.Text
	Location                     pgtype.Text
	Sort                         string
	PageOffset                   int32
	PageSize                     int32
}

func (q *Queries) ListPublicJobs(ctx context.Context, arg ListPublicJobsParams) ([]JobhubJob, error) {
	rows, err := q.db.Query(ctx, listPublicJobs,
		arg.RequireProductionPermissions,
		arg.Query,
		arg.Location,
		arg.Sort,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobhubJob
	for rows.Next() {
		var i JobhubJob
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.SourceUrl,
			&i.UpstreamSourceName,
			&i.CompanyID,
			&i.CompanySourceID,
			&i.CompanyNameRaw,
			&i.Title,
			&i.LocationRaw,
			&i.Description,
			&i.DescriptionKind,
			&i.EmploymentTypeRaw,
			&i.SalaryRaw,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.SalaryCurrency,
			&i.SalaryPeriod,
			&i.SalaryGross,
			&i.SalaryIsEstimated,
			&i.ApplicationMethod,
			&i.ApplyUrl,
			&i.SourceStatus,
			&i.PublicationStatus,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.LastSyncedAt,
			&i.FreshUntil,
			&i.ExternalCreatedAt,
			&i.ExternalPublishedAt,
			&i.ExternalUpdatedAt,
			&i.ExternalUpdatedRaw,
			&i.ExternalExpiresAt,
			&i.ExternalArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertImportedJob = `-- name: UpsertImportedJob :one
INSERT INTO jobhub.jobs (
    source,
    external_id,
    source_url,
    upstream_source_name,
    company_name_raw,
    title,
    location_raw,
    description,
    description_kind,
    employment_type_raw,
    salary_raw,
    application_method,
    apply_url,
    source_status,
    first_seen_at,
    last_seen_at,
    last_synced_at,
    fresh_until,
    external_updated_at,
    external_updated_raw
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    'external',
    $3,
    'unknown',
    $12,
    $12,
    $12,
    $13,
    $14,
    $15
)
ON CONFLICT (source, external_id) DO UPDATE SET
    source_url = EXCLUDED.source_url,
    upstream_source_name = EXCLUDED.upstream_source_name,
    company_name_raw = EXCLUDED.company_name_raw,
    title = EXCLUDED.title,
    location_raw = EXCLUDED.location_raw,
    description = EXCLUDED.description,
    description_kind = EXCLUDED.description_kind,
    employment_type_raw = EXCLUDED.employment_type_raw,
    salary_raw = EXCLUDED.salary_raw,
    apply_url = EXCLUDED.apply_url,
    last_seen_at = EXCLUDED.last_seen_at,
    last_synced_at = EXCLUDED.last_synced_at,
    fresh_until = EXCLUDED.fresh_until,
    external_updated_at = EXCLUDED.external_updated_at,
    external_updated_raw = EXCLUDED.external_updated_raw,
    updated_at = now()
WHERE jobhub.jobs.last_synced_at <= EXCLUDED.last_synced_at
RETURNING id
`

type UpsertImportedJobParams struct {
	Source             string
	ExternalID         pgtype.Text
	SourceUrl          pgtype.Text
	UpstreamSourceName pgtype.Text
	CompanyNameRaw     pgtype.Text
	Title              string
	LocationRaw        pgtype.Text
	Description        pgtype.Text
	DescriptionKind    string
	EmploymentTypeRaw  pgtype.Text
	SalaryRaw          pgtype.Text
	ObservedAt         pgtype.Timestamptz
	FreshUntil         pgtype.Timestamptz
	ExternalUpdatedAt  pgtype.Timestamptz
	ExternalUpdatedRaw pgtype.Text
}

func (q *Queries) UpsertImportedJob(ctx context.Context, arg UpsertImportedJobParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertImportedJob,
		arg.Source,
		arg.ExternalID,
		arg.SourceUrl,
		arg.UpstreamSourceName,
		arg.CompanyNameRaw,
		arg.Title,
		arg.LocationRaw,
		arg.Description,
		arg.DescriptionKind,
		arg.EmploymentTypeRaw,
		arg.SalaryRaw,
		arg.ObservedAt,
		arg.FreshUntil,
		arg.ExternalUpdatedAt,
		arg.ExternalUpdatedRaw,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
