// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: jobs.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireSourceIngestionLock = `-- name: AcquireSourceIngestionLock :exec
SELECT pg_advisory_xact_lock(hashtextextended($1, 0))
`

func (q *Queries) AcquireSourceIngestionLock(ctx context.Context, source string) error {
	_, err := q.db.Exec(ctx, acquireSourceIngestionLock, source)
	return err
}

const completeIngestionRun = `-- name: CompleteIngestionRun :exec
UPDATE jobhub.ingestion_runs
SET status = 'succeeded',
    request_count = $1,
    fetched_count = $2,
    normalized_count = $3,
    inserted_count = $4,
    updated_count = $5,
    skipped_count = $6,
    finished_at = now()
WHERE id = $7 AND status = 'running'
`

type CompleteIngestionRunParams struct {
	RequestCount    int32
	FetchedCount    int32
	NormalizedCount int32
	InsertedCount   int32
	UpdatedCount    int32
	SkippedCount    int32
	ID              pgtype.UUID
}

func (q *Queries) CompleteIngestionRun(ctx context.Context, arg CompleteIngestionRunParams) error {
	_, err := q.db.Exec(ctx, completeIngestionRun,
		arg.RequestCount,
		arg.FetchedCount,
		arg.NormalizedCount,
		arg.InsertedCount,
		arg.UpdatedCount,
		arg.SkippedCount,
		arg.ID,
	)
	return err
}

const countPublicJobs = `-- name: CountPublicJobs :one
SELECT count(*)
FROM jobhub.jobs j
JOIN jobhub.job_sources s ON s.source = j.source
WHERE s.enabled
  AND (NOT $1::boolean OR s.production_permissions_confirmed)
  AND jobhub.job_is_public(j)
  AND ($2::text IS NULL OR j.title ILIKE '%' || $2 || '%' OR j.company_name_raw ILIKE '%' || $2 || '%' OR EXISTS (SELECT 1 FROM unnest(j.skills) skill WHERE skill ILIKE '%' || $2 || '%'))
  AND ($3::text IS NULL OR j.canonical_city_id = $3)
  AND (COALESCE(cardinality($4::text[]), 0) = 0 OR j.work_mode = ANY($4::text[]))
  AND ($5::numeric IS NULL OR (j.salary_visible AND j.salary_currency = $6 AND j.salary_period = 'month' AND COALESCE(j.salary_max, j.salary_min) >= $5))
  AND ($7::text IS NULL OR j.experience_level = $7)
  AND ($8::text IS NULL OR j.employment_type = $8)
  AND ($9::timestamptz IS NULL OR COALESCE(j.external_published_at, j.published_at, j.first_seen_at) >= $9)
`

type CountPublicJobsParams struct {
	RequireProductionPermissions bool
	Query                        pgtype.Text
	City                         pgtype.Text
	WorkModes                    []string
	SalaryMin                    pgtype.Numeric
	Currency                     pgtype.Text
	ExperienceLevel              pgtype.Text
	EmploymentType               pgtype.Text
	PostedAfter                  pgtype.Timestamptz
}

func (q *Queries) CountPublicJobs(ctx context.Context, arg CountPublicJobsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicJobs,
		arg.RequireProductionPermissions,
		arg.Query,
		arg.City,
		arg.WorkModes,
		arg.SalaryMin,
		arg.Currency,
		arg.ExperienceLevel,
		arg.EmploymentType,
		arg.PostedAfter,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIngestionRun = `-- name: CreateIngestionRun :one
INSERT INTO jobhub.ingestion_runs (source, search_count)
VALUES ($1, $2)
RETURNING id
`

type CreateIngestionRunParams struct {
	Source      string
	SearchCount int32
}

func (q *Queries) CreateIngestionRun(ctx context.Context, arg CreateIngestionRunParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createIngestionRun, arg.Source, arg.SearchCount)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createNativeJob = `-- name: CreateNativeJob :one
INSERT INTO jobhub.jobs (
    source, company_id, created_by_user_id, company_name_raw, title, category, description, description_kind,
    responsibilities, requirements, nice_to_have, skills, location_raw, canonical_city_id,
    work_mode, employment_type, experience_level, salary_min, salary_max,
    salary_currency, salary_period, salary_visible, benefits, application_method,
    source_status, publication_status, first_seen_at, last_seen_at, last_synced_at,
    fresh_until, expires_at, moderation_status
)
SELECT
    'jobhub', cm.company_id, $1, c.name, $2, $3,
    $4, 'full', $5, $6,
    $7, $8::text[], $9, $10,
    $11, $12, $13,
    $14, $15, $16,
    $17, $18, $19::text[],
    'internal', 'active', 'draft', now(), now(), now(), 'infinity'::timestamptz,
    $20, 'approved'
FROM jobhub.company_memberships cm
JOIN jobhub.companies c ON c.id = cm.company_id
JOIN jobhub.users u ON u.id = cm.user_id
WHERE cm.user_id = $1
  AND cm.role = 'owner'
  AND c.status = 'active'
  AND u.status = 'active'
ORDER BY cm.created_at
LIMIT 1
RETURNING id, source, external_id, source_url, upstream_source_name, company_id, company_source_id, company_name_raw, title, location_raw, description, description_kind, employment_type_raw, salary_raw, salary_min, salary_max, salary_currency, salary_period, salary_gross, salary_is_estimated, application_method, apply_url, source_status, publication_status, first_seen_at, last_seen_at, last_synced_at, fresh_until, external_created_at, external_published_at, external_updated_at, external_updated_raw, external_expires_at, external_archived_at, created_at, updated_at, category, responsibilities, requirements, nice_to_have, skills, work_mode, employment_type, experience_level, benefits, salary_visible, expires_at, published_at, deleted_at, moderation_status, created_by_user_id, canonical_city_id
`

type CreateNativeJobParams struct {
	UserID           pgtype.UUID
	Title            string
	Category         pgtype.Text
	Description      pgtype.Text
	Responsibilities pgtype.Text
	Requirements     pgtype.Text
	NiceToHave       pgtype.Text
	Skills           []string
	Location         pgtype.Text
	CanonicalCityID  pgtype.Text
	WorkMode         pgtype.Text
	EmploymentType   pgtype.Text
	ExperienceLevel  pgtype.Text
	SalaryMin        pgtype.Numeric
	SalaryMax        pgtype.Numeric
	SalaryCurrency   pgtype.Text
	SalaryPeriod     pgtype.Text
	SalaryVisible    bool
	Benefits         []string
	ExpiresAt        pgtype.Timestamptz
}

func (q *Queries) CreateNativeJob(ctx context.Context, arg CreateNativeJobParams) (JobhubJob, error) {
	row := q.db.QueryRow(ctx, createNativeJob,
		arg.UserID,
		arg.Title,
		arg.Category,
		arg.Description,
		arg.Responsibilities,
		arg.Requirements,
		arg.NiceToHave,
		arg.Skills,
		arg.Location,
		arg.CanonicalCityID,
		arg.WorkMode,
		arg.EmploymentType,
		arg.ExperienceLevel,
		arg.SalaryMin,
		arg.SalaryMax,
		arg.SalaryCurrency,
		arg.SalaryPeriod,
		arg.SalaryVisible,
		arg.Benefits,
		arg.ExpiresAt,
	)
	var i JobhubJob
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.SourceUrl,
		&i.UpstreamSourceName,
		&i.CompanyID,
		&i.CompanySourceID,
		&i.CompanyNameRaw,
		&i.Title,
		&i.LocationRaw,
		&i.Description,
		&i.DescriptionKind,
		&i.EmploymentTypeRaw,
		&i.SalaryRaw,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.SalaryPeriod,
		&i.SalaryGross,
		&i.SalaryIsEstimated,
		&i.ApplicationMethod,
		&i.ApplyUrl,
		&i.SourceStatus,
		&i.PublicationStatus,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.LastSyncedAt,
		&i.FreshUntil,
		&i.ExternalCreatedAt,
		&i.ExternalPublishedAt,
		&i.ExternalUpdatedAt,
		&i.ExternalUpdatedRaw,
		&i.ExternalExpiresAt,
		&i.ExternalArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Responsibilities,
		&i.Requirements,
		&i.NiceToHave,
		&i.Skills,
		&i.WorkMode,
		&i.EmploymentType,
		&i.ExperienceLevel,
		&i.Benefits,
		&i.SalaryVisible,
		&i.ExpiresAt,
		&i.PublishedAt,
		&i.DeletedAt,
		&i.ModerationStatus,
		&i.CreatedByUserID,
		&i.CanonicalCityID,
	)
	return i, err
}

const failIngestionRun = `-- name: FailIngestionRun :exec
UPDATE jobhub.ingestion_runs
SET status = 'failed',
    request_count = $1,
    fetched_count = $2,
    normalized_count = $3,
    error_code = $4,
    error_message = $5,
    finished_at = now()
WHERE id = $6 AND status = 'running'
`

type FailIngestionRunParams struct {
	RequestCount    int32
	FetchedCount    int32
	NormalizedCount int32
	ErrorCode       pgtype.Text
	ErrorMessage    pgtype.Text
	ID              pgtype.UUID
}

func (q *Queries) FailIngestionRun(ctx context.Context, arg FailIngestionRunParams) error {
	_, err := q.db.Exec(ctx, failIngestionRun,
		arg.RequestCount,
		arg.FetchedCount,
		arg.NormalizedCount,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}

const getEmployerJob = `-- name: GetEmployerJob :one
SELECT j.id, j.source, j.external_id, j.source_url, j.upstream_source_name, j.company_id, j.company_source_id, j.company_name_raw, j.title, j.location_raw, j.description, j.description_kind, j.employment_type_raw, j.salary_raw, j.salary_min, j.salary_max, j.salary_currency, j.salary_period, j.salary_gross, j.salary_is_estimated, j.application_method, j.apply_url, j.source_status, j.publication_status, j.first_seen_at, j.last_seen_at, j.last_synced_at, j.fresh_until, j.external_created_at, j.external_published_at, j.external_updated_at, j.external_updated_raw, j.external_expires_at, j.external_archived_at, j.created_at, j.updated_at, j.category, j.responsibilities, j.requirements, j.nice_to_have, j.skills, j.work_mode, j.employment_type, j.experience_level, j.benefits, j.salary_visible, j.expires_at, j.published_at, j.deleted_at, j.moderation_status, j.created_by_user_id, j.canonical_city_id
FROM jobhub.jobs j
JOIN jobhub.company_memberships cm ON cm.company_id = j.company_id
WHERE j.id = $1
  AND cm.user_id = $2
  AND cm.role = 'owner'
  AND j.source = 'jobhub'
  AND j.deleted_at IS NULL
`

type GetEmployerJobParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetEmployerJob(ctx context.Context, arg GetEmployerJobParams) (JobhubJob, error) {
	row := q.db.QueryRow(ctx, getEmployerJob, arg.ID, arg.UserID)
	var i JobhubJob
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.SourceUrl,
		&i.UpstreamSourceName,
		&i.CompanyID,
		&i.CompanySourceID,
		&i.CompanyNameRaw,
		&i.Title,
		&i.LocationRaw,
		&i.Description,
		&i.DescriptionKind,
		&i.EmploymentTypeRaw,
		&i.SalaryRaw,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.SalaryPeriod,
		&i.SalaryGross,
		&i.SalaryIsEstimated,
		&i.ApplicationMethod,
		&i.ApplyUrl,
		&i.SourceStatus,
		&i.PublicationStatus,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.LastSyncedAt,
		&i.FreshUntil,
		&i.ExternalCreatedAt,
		&i.ExternalPublishedAt,
		&i.ExternalUpdatedAt,
		&i.ExternalUpdatedRaw,
		&i.ExternalExpiresAt,
		&i.ExternalArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Responsibilities,
		&i.Requirements,
		&i.NiceToHave,
		&i.Skills,
		&i.WorkMode,
		&i.EmploymentType,
		&i.ExperienceLevel,
		&i.Benefits,
		&i.SalaryVisible,
		&i.ExpiresAt,
		&i.PublishedAt,
		&i.DeletedAt,
		&i.ModerationStatus,
		&i.CreatedByUserID,
		&i.CanonicalCityID,
	)
	return i, err
}

const getPublicJob = `-- name: GetPublicJob :one
SELECT j.id, j.source, j.external_id, j.source_url, j.upstream_source_name, j.company_id, j.company_source_id, j.company_name_raw, j.title, j.location_raw, j.description, j.description_kind, j.employment_type_raw, j.salary_raw, j.salary_min, j.salary_max, j.salary_currency, j.salary_period, j.salary_gross, j.salary_is_estimated, j.application_method, j.apply_url, j.source_status, j.publication_status, j.first_seen_at, j.last_seen_at, j.last_synced_at, j.fresh_until, j.external_created_at, j.external_published_at, j.external_updated_at, j.external_updated_raw, j.external_expires_at, j.external_archived_at, j.created_at, j.updated_at, j.category, j.responsibilities, j.requirements, j.nice_to_have, j.skills, j.work_mode, j.employment_type, j.experience_level, j.benefits, j.salary_visible, j.expires_at, j.published_at, j.deleted_at, j.moderation_status, j.created_by_user_id, j.canonical_city_id
FROM jobhub.jobs j
JOIN jobhub.job_sources s ON s.source = j.source
WHERE j.id = $1
  AND s.enabled
  AND (NOT $2::boolean OR s.production_permissions_confirmed)
  AND jobhub.job_is_public(j)
`

type GetPublicJobParams struct {
	ID                           pgtype.UUID
	RequireProductionPermissions bool
}

func (q *Queries) GetPublicJob(ctx context.Context, arg GetPublicJobParams) (JobhubJob, error) {
	row := q.db.QueryRow(ctx, getPublicJob, arg.ID, arg.RequireProductionPermissions)
	var i JobhubJob
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.SourceUrl,
		&i.UpstreamSourceName,
		&i.CompanyID,
		&i.CompanySourceID,
		&i.CompanyNameRaw,
		&i.Title,
		&i.LocationRaw,
		&i.Description,
		&i.DescriptionKind,
		&i.EmploymentTypeRaw,
		&i.SalaryRaw,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.SalaryPeriod,
		&i.SalaryGross,
		&i.SalaryIsEstimated,
		&i.ApplicationMethod,
		&i.ApplyUrl,
		&i.SourceStatus,
		&i.PublicationStatus,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.LastSyncedAt,
		&i.FreshUntil,
		&i.ExternalCreatedAt,
		&i.ExternalPublishedAt,
		&i.ExternalUpdatedAt,
		&i.ExternalUpdatedRaw,
		&i.ExternalExpiresAt,
		&i.ExternalArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Responsibilities,
		&i.Requirements,
		&i.NiceToHave,
		&i.Skills,
		&i.WorkMode,
		&i.EmploymentType,
		&i.ExperienceLevel,
		&i.Benefits,
		&i.SalaryVisible,
		&i.ExpiresAt,
		&i.PublishedAt,
		&i.DeletedAt,
		&i.ModerationStatus,
		&i.CreatedByUserID,
		&i.CanonicalCityID,
	)
	return i, err
}

const importedJobExists = `-- name: ImportedJobExists :one
SELECT EXISTS (
    SELECT 1 FROM jobhub.jobs
    WHERE source = $1 AND external_id = $2
)
`

type ImportedJobExistsParams struct {
	Source     string
	ExternalID pgtype.Text
}

func (q *Queries) ImportedJobExists(ctx context.Context, arg ImportedJobExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, importedJobExists, arg.Source, arg.ExternalID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listEmployerJobs = `-- name: ListEmployerJobs :many
SELECT j.id, j.source, j.external_id, j.source_url, j.upstream_source_name, j.company_id, j.company_source_id, j.company_name_raw, j.title, j.location_raw, j.description, j.description_kind, j.employment_type_raw, j.salary_raw, j.salary_min, j.salary_max, j.salary_currency, j.salary_period, j.salary_gross, j.salary_is_estimated, j.application_method, j.apply_url, j.source_status, j.publication_status, j.first_seen_at, j.last_seen_at, j.last_synced_at, j.fresh_until, j.external_created_at, j.external_published_at, j.external_updated_at, j.external_updated_raw, j.external_expires_at, j.external_archived_at, j.created_at, j.updated_at, j.category, j.responsibilities, j.requirements, j.nice_to_have, j.skills, j.work_mode, j.employment_type, j.experience_level, j.benefits, j.salary_visible, j.expires_at, j.published_at, j.deleted_at, j.moderation_status, j.created_by_user_id, j.canonical_city_id
FROM jobhub.jobs j
JOIN jobhub.company_memberships cm ON cm.company_id = j.company_id
WHERE cm.user_id = $1
  AND cm.role = 'owner'
  AND j.source = 'jobhub'
  AND j.deleted_at IS NULL
ORDER BY j.updated_at DESC, j.id DESC
`

func (q *Queries) ListEmployerJobs(ctx context.Context, userID pgtype.UUID) ([]JobhubJob, error) {
	rows, err := q.db.Query(ctx, listEmployerJobs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobhubJob
	for rows.Next() {
		var i JobhubJob
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.SourceUrl,
			&i.UpstreamSourceName,
			&i.CompanyID,
			&i.CompanySourceID,
			&i.CompanyNameRaw,
			&i.Title,
			&i.LocationRaw,
			&i.Description,
			&i.DescriptionKind,
			&i.EmploymentTypeRaw,
			&i.SalaryRaw,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.SalaryCurrency,
			&i.SalaryPeriod,
			&i.SalaryGross,
			&i.SalaryIsEstimated,
			&i.ApplicationMethod,
			&i.ApplyUrl,
			&i.SourceStatus,
			&i.PublicationStatus,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.LastSyncedAt,
			&i.FreshUntil,
			&i.ExternalCreatedAt,
			&i.ExternalPublishedAt,
			&i.ExternalUpdatedAt,
			&i.ExternalUpdatedRaw,
			&i.ExternalExpiresAt,
			&i.ExternalArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
			&i.Responsibilities,
			&i.Requirements,
			&i.NiceToHave,
			&i.Skills,
			&i.WorkMode,
			&i.EmploymentType,
			&i.ExperienceLevel,
			&i.Benefits,
			&i.SalaryVisible,
			&i.ExpiresAt,
			&i.PublishedAt,
			&i.DeletedAt,
			&i.ModerationStatus,
			&i.CreatedByUserID,
			&i.CanonicalCityID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicJobs = `-- name: ListPublicJobs :many
SELECT j.id, j.source, j.external_id, j.source_url, j.upstream_source_name, j.company_id, j.company_source_id, j.company_name_raw, j.title, j.location_raw, j.description, j.description_kind, j.employment_type_raw, j.salary_raw, j.salary_min, j.salary_max, j.salary_currency, j.salary_period, j.salary_gross, j.salary_is_estimated, j.application_method, j.apply_url, j.source_status, j.publication_status, j.first_seen_at, j.last_seen_at, j.last_synced_at, j.fresh_until, j.external_created_at, j.external_published_at, j.external_updated_at, j.external_updated_raw, j.external_expires_at, j.external_archived_at, j.created_at, j.updated_at, j.category, j.responsibilities, j.requirements, j.nice_to_have, j.skills, j.work_mode, j.employment_type, j.experience_level, j.benefits, j.salary_visible, j.expires_at, j.published_at, j.deleted_at, j.moderation_status, j.created_by_user_id, j.canonical_city_id
FROM jobhub.jobs j
JOIN jobhub.job_sources s ON s.source = j.source
WHERE s.enabled
  AND (NOT $1::boolean OR s.production_permissions_confirmed)
  AND jobhub.job_is_public(j)
  AND ($2::text IS NULL OR j.title ILIKE '%' || $2 || '%' OR j.company_name_raw ILIKE '%' || $2 || '%' OR EXISTS (SELECT 1 FROM unnest(j.skills) skill WHERE skill ILIKE '%' || $2 || '%'))
  AND ($3::text IS NULL OR j.canonical_city_id = $3)
  AND (COALESCE(cardinality($4::text[]), 0) = 0 OR j.work_mode = ANY($4::text[]))
  AND ($5::numeric IS NULL OR (j.salary_visible AND j.salary_currency = $6 AND j.salary_period = 'month' AND COALESCE(j.salary_max, j.salary_min) >= $5))
  AND ($7::text IS NULL OR j.experience_level = $7)
  AND ($8::text IS NULL OR j.employment_type = $8)
  AND ($9::timestamptz IS NULL OR COALESCE(j.external_published_at, j.published_at, j.first_seen_at) >= $9)
ORDER BY
    CASE WHEN $10::text IS NOT NULL AND j.canonical_city_id = $10 THEN 0 ELSE 1 END,
    CASE WHEN $11::text = 'oldest' THEN COALESCE(j.external_published_at, j.first_seen_at) END ASC,
    CASE WHEN $11::text <> 'oldest' THEN COALESCE(j.external_published_at, j.first_seen_at) END DESC,
    j.id DESC
LIMIT $13 OFFSET $12
`

type ListPublicJobsParams struct {
	RequireProductionPermissions bool
	Query                        pgtype.Text
	City                         pgtype.Text
	WorkModes                    []string
	SalaryMin                    pgtype.Numeric
	Currency                     pgtype.Text
	ExperienceLevel              pgtype.Text
	EmploymentType               pgtype.Text
	PostedAfter                  pgtype.Timestamptz
	PreferredCity                pgtype.Text
	Sort                         string
	PageOffset                   int32
	PageSize                     int32
}

func (q *Queries) ListPublicJobs(ctx context.Context, arg ListPublicJobsParams) ([]JobhubJob, error) {
	rows, err := q.db.Query(ctx, listPublicJobs,
		arg.RequireProductionPermissions,
		arg.Query,
		arg.City,
		arg.WorkModes,
		arg.SalaryMin,
		arg.Currency,
		arg.ExperienceLevel,
		arg.EmploymentType,
		arg.PostedAfter,
		arg.PreferredCity,
		arg.Sort,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobhubJob
	for rows.Next() {
		var i JobhubJob
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.SourceUrl,
			&i.UpstreamSourceName,
			&i.CompanyID,
			&i.CompanySourceID,
			&i.CompanyNameRaw,
			&i.Title,
			&i.LocationRaw,
			&i.Description,
			&i.DescriptionKind,
			&i.EmploymentTypeRaw,
			&i.SalaryRaw,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.SalaryCurrency,
			&i.SalaryPeriod,
			&i.SalaryGross,
			&i.SalaryIsEstimated,
			&i.ApplicationMethod,
			&i.ApplyUrl,
			&i.SourceStatus,
			&i.PublicationStatus,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.LastSyncedAt,
			&i.FreshUntil,
			&i.ExternalCreatedAt,
			&i.ExternalPublishedAt,
			&i.ExternalUpdatedAt,
			&i.ExternalUpdatedRaw,
			&i.ExternalExpiresAt,
			&i.ExternalArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
			&i.Responsibilities,
			&i.Requirements,
			&i.NiceToHave,
			&i.Skills,
			&i.WorkMode,
			&i.EmploymentType,
			&i.ExperienceLevel,
			&i.Benefits,
			&i.SalaryVisible,
			&i.ExpiresAt,
			&i.PublishedAt,
			&i.DeletedAt,
			&i.ModerationStatus,
			&i.CreatedByUserID,
			&i.CanonicalCityID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteNativeJob = `-- name: SoftDeleteNativeJob :one
UPDATE jobhub.jobs j
SET deleted_at = now(), updated_at = now()
WHERE j.id = $1
  AND j.source = 'jobhub'
  AND j.deleted_at IS NULL
  AND j.publication_status IN ('draft', 'closed')
  AND EXISTS (
      SELECT 1 FROM jobhub.company_memberships cm
      WHERE cm.company_id = j.company_id
        AND cm.user_id = $2
        AND cm.role = 'owner'
  )
RETURNING j.id
`

type SoftDeleteNativeJobParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) SoftDeleteNativeJob(ctx context.Context, arg SoftDeleteNativeJobParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteNativeJob, arg.ID, arg.UserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const transitionNativeJob = `-- name: TransitionNativeJob :one
UPDATE jobhub.jobs j
SET publication_status = $1,
    published_at = CASE
        WHEN $1::text = 'published' THEN COALESCE(j.published_at, now())
        ELSE j.published_at
    END,
    updated_at = now()
WHERE j.id = $2
  AND j.source = 'jobhub'
  AND j.deleted_at IS NULL
  AND (
      j.publication_status = $1
      OR (j.publication_status = 'draft' AND $1::text IN ('published', 'closed'))
      OR (j.publication_status = 'published' AND $1::text IN ('paused', 'closed'))
      OR (j.publication_status = 'paused' AND $1::text IN ('published', 'closed'))
  )
  AND EXISTS (
      SELECT 1 FROM jobhub.company_memberships cm
      WHERE cm.company_id = j.company_id
        AND cm.user_id = $3
        AND cm.role = 'owner'
  )
RETURNING j.id, j.source, j.external_id, j.source_url, j.upstream_source_name, j.company_id, j.company_source_id, j.company_name_raw, j.title, j.location_raw, j.description, j.description_kind, j.employment_type_raw, j.salary_raw, j.salary_min, j.salary_max, j.salary_currency, j.salary_period, j.salary_gross, j.salary_is_estimated, j.application_method, j.apply_url, j.source_status, j.publication_status, j.first_seen_at, j.last_seen_at, j.last_synced_at, j.fresh_until, j.external_created_at, j.external_published_at, j.external_updated_at, j.external_updated_raw, j.external_expires_at, j.external_archived_at, j.created_at, j.updated_at, j.category, j.responsibilities, j.requirements, j.nice_to_have, j.skills, j.work_mode, j.employment_type, j.experience_level, j.benefits, j.salary_visible, j.expires_at, j.published_at, j.deleted_at, j.moderation_status, j.created_by_user_id, j.canonical_city_id
`

type TransitionNativeJobParams struct {
	PublicationStatus pgtype.Text
	ID                pgtype.UUID
	UserID            pgtype.UUID
}

func (q *Queries) TransitionNativeJob(ctx context.Context, arg TransitionNativeJobParams) (JobhubJob, error) {
	row := q.db.QueryRow(ctx, transitionNativeJob, arg.PublicationStatus, arg.ID, arg.UserID)
	var i JobhubJob
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.SourceUrl,
		&i.UpstreamSourceName,
		&i.CompanyID,
		&i.CompanySourceID,
		&i.CompanyNameRaw,
		&i.Title,
		&i.LocationRaw,
		&i.Description,
		&i.DescriptionKind,
		&i.EmploymentTypeRaw,
		&i.SalaryRaw,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.SalaryPeriod,
		&i.SalaryGross,
		&i.SalaryIsEstimated,
		&i.ApplicationMethod,
		&i.ApplyUrl,
		&i.SourceStatus,
		&i.PublicationStatus,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.LastSyncedAt,
		&i.FreshUntil,
		&i.ExternalCreatedAt,
		&i.ExternalPublishedAt,
		&i.ExternalUpdatedAt,
		&i.ExternalUpdatedRaw,
		&i.ExternalExpiresAt,
		&i.ExternalArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Responsibilities,
		&i.Requirements,
		&i.NiceToHave,
		&i.Skills,
		&i.WorkMode,
		&i.EmploymentType,
		&i.ExperienceLevel,
		&i.Benefits,
		&i.SalaryVisible,
		&i.ExpiresAt,
		&i.PublishedAt,
		&i.DeletedAt,
		&i.ModerationStatus,
		&i.CreatedByUserID,
		&i.CanonicalCityID,
	)
	return i, err
}

const updateNativeJob = `-- name: UpdateNativeJob :one
UPDATE jobhub.jobs j
SET title = $1,
    category = $2,
    description = $3,
    responsibilities = $4,
    requirements = $5,
    nice_to_have = $6,
    skills = $7::text[],
    location_raw = $8,
    canonical_city_id = $9,
    work_mode = $10,
    employment_type = $11,
    experience_level = $12,
    salary_min = $13,
    salary_max = $14,
    salary_currency = $15,
    salary_period = $16,
    salary_visible = $17,
    benefits = $18::text[],
    expires_at = $19,
    updated_at = now()
WHERE j.id = $20
  AND j.source = 'jobhub'
  AND j.deleted_at IS NULL
  AND j.publication_status <> 'closed'
  AND EXISTS (
      SELECT 1 FROM jobhub.company_memberships cm
      WHERE cm.company_id = j.company_id
        AND cm.user_id = $21
        AND cm.role = 'owner'
  )
RETURNING j.id, j.source, j.external_id, j.source_url, j.upstream_source_name, j.company_id, j.company_source_id, j.company_name_raw, j.title, j.location_raw, j.description, j.description_kind, j.employment_type_raw, j.salary_raw, j.salary_min, j.salary_max, j.salary_currency, j.salary_period, j.salary_gross, j.salary_is_estimated, j.application_method, j.apply_url, j.source_status, j.publication_status, j.first_seen_at, j.last_seen_at, j.last_synced_at, j.fresh_until, j.external_created_at, j.external_published_at, j.external_updated_at, j.external_updated_raw, j.external_expires_at, j.external_archived_at, j.created_at, j.updated_at, j.category, j.responsibilities, j.requirements, j.nice_to_have, j.skills, j.work_mode, j.employment_type, j.experience_level, j.benefits, j.salary_visible, j.expires_at, j.published_at, j.deleted_at, j.moderation_status, j.created_by_user_id, j.canonical_city_id
`

type UpdateNativeJobParams struct {
	Title            string
	Category         pgtype.Text
	Description      pgtype.Text
	Responsibilities pgtype.Text
	Requirements     pgtype.Text
	NiceToHave       pgtype.Text
	Skills           []string
	Location         pgtype.Text
	CanonicalCityID  pgtype.Text
	WorkMode         pgtype.Text
	EmploymentType   pgtype.Text
	ExperienceLevel  pgtype.Text
	SalaryMin        pgtype.Numeric
	SalaryMax        pgtype.Numeric
	SalaryCurrency   pgtype.Text
	SalaryPeriod     pgtype.Text
	SalaryVisible    bool
	Benefits         []string
	ExpiresAt        pgtype.Timestamptz
	ID               pgtype.UUID
	UserID           pgtype.UUID
}

func (q *Queries) UpdateNativeJob(ctx context.Context, arg UpdateNativeJobParams) (JobhubJob, error) {
	row := q.db.QueryRow(ctx, updateNativeJob,
		arg.Title,
		arg.Category,
		arg.Description,
		arg.Responsibilities,
		arg.Requirements,
		arg.NiceToHave,
		arg.Skills,
		arg.Location,
		arg.CanonicalCityID,
		arg.WorkMode,
		arg.EmploymentType,
		arg.ExperienceLevel,
		arg.SalaryMin,
		arg.SalaryMax,
		arg.SalaryCurrency,
		arg.SalaryPeriod,
		arg.SalaryVisible,
		arg.Benefits,
		arg.ExpiresAt,
		arg.ID,
		arg.UserID,
	)
	var i JobhubJob
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.SourceUrl,
		&i.UpstreamSourceName,
		&i.CompanyID,
		&i.CompanySourceID,
		&i.CompanyNameRaw,
		&i.Title,
		&i.LocationRaw,
		&i.Description,
		&i.DescriptionKind,
		&i.EmploymentTypeRaw,
		&i.SalaryRaw,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.SalaryCurrency,
		&i.SalaryPeriod,
		&i.SalaryGross,
		&i.SalaryIsEstimated,
		&i.ApplicationMethod,
		&i.ApplyUrl,
		&i.SourceStatus,
		&i.PublicationStatus,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.LastSyncedAt,
		&i.FreshUntil,
		&i.ExternalCreatedAt,
		&i.ExternalPublishedAt,
		&i.ExternalUpdatedAt,
		&i.ExternalUpdatedRaw,
		&i.ExternalExpiresAt,
		&i.ExternalArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Responsibilities,
		&i.Requirements,
		&i.NiceToHave,
		&i.Skills,
		&i.WorkMode,
		&i.EmploymentType,
		&i.ExperienceLevel,
		&i.Benefits,
		&i.SalaryVisible,
		&i.ExpiresAt,
		&i.PublishedAt,
		&i.DeletedAt,
		&i.ModerationStatus,
		&i.CreatedByUserID,
		&i.CanonicalCityID,
	)
	return i, err
}

const upsertImportedJob = `-- name: UpsertImportedJob :one
INSERT INTO jobhub.jobs (
    source,
    external_id,
    source_url,
    upstream_source_name,
    company_name_raw,
    title,
    location_raw,
    canonical_city_id,
    description,
    description_kind,
    employment_type_raw,
    salary_raw,
    category,
    application_method,
    apply_url,
    source_status,
    first_seen_at,
    last_seen_at,
    last_synced_at,
    fresh_until,
    external_published_at,
    external_updated_at,
    external_updated_raw,
    external_expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    'external',
    $3,
    'unknown',
    $14,
    $14,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19
)
ON CONFLICT (source, external_id) DO UPDATE SET
    source_url = EXCLUDED.source_url,
    upstream_source_name = EXCLUDED.upstream_source_name,
    company_name_raw = EXCLUDED.company_name_raw,
    title = EXCLUDED.title,
    location_raw = EXCLUDED.location_raw,
    canonical_city_id = EXCLUDED.canonical_city_id,
    description = EXCLUDED.description,
    description_kind = EXCLUDED.description_kind,
    employment_type_raw = EXCLUDED.employment_type_raw,
    salary_raw = EXCLUDED.salary_raw,
    category = EXCLUDED.category,
    apply_url = EXCLUDED.apply_url,
    last_seen_at = EXCLUDED.last_seen_at,
    last_synced_at = EXCLUDED.last_synced_at,
    fresh_until = EXCLUDED.fresh_until,
    external_published_at = EXCLUDED.external_published_at,
    external_updated_at = EXCLUDED.external_updated_at,
    external_updated_raw = EXCLUDED.external_updated_raw,
    external_expires_at = EXCLUDED.external_expires_at,
    updated_at = now()
WHERE jobhub.jobs.last_synced_at <= EXCLUDED.last_synced_at
RETURNING id
`

type UpsertImportedJobParams struct {
	Source              string
	ExternalID          pgtype.Text
	SourceUrl           pgtype.Text
	UpstreamSourceName  pgtype.Text
	CompanyNameRaw      pgtype.Text
	Title               string
	LocationRaw         pgtype.Text
	CanonicalCityID     pgtype.Text
	Description         pgtype.Text
	DescriptionKind     string
	EmploymentTypeRaw   pgtype.Text
	SalaryRaw           pgtype.Text
	Category            pgtype.Text
	ObservedAt          pgtype.Timestamptz
	FreshUntil          pgtype.Timestamptz
	ExternalPublishedAt pgtype.Timestamptz
	ExternalUpdatedAt   pgtype.Timestamptz
	ExternalUpdatedRaw  pgtype.Text
	ExternalExpiresAt   pgtype.Timestamptz
}

func (q *Queries) UpsertImportedJob(ctx context.Context, arg UpsertImportedJobParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertImportedJob,
		arg.Source,
		arg.ExternalID,
		arg.SourceUrl,
		arg.UpstreamSourceName,
		arg.CompanyNameRaw,
		arg.Title,
		arg.LocationRaw,
		arg.CanonicalCityID,
		arg.Description,
		arg.DescriptionKind,
		arg.EmploymentTypeRaw,
		arg.SalaryRaw,
		arg.Category,
		arg.ObservedAt,
		arg.FreshUntil,
		arg.ExternalPublishedAt,
		arg.ExternalUpdatedAt,
		arg.ExternalUpdatedRaw,
		arg.ExternalExpiresAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
