// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CompanyDuplicateMap struct {
	DuplicateID pgtype.UUID
	CanonicalID interface{}
}

type JobhubApplication struct {
	ID          pgtype.UUID
	JobID       pgtype.UUID
	CompanyID   pgtype.UUID
	CandidateID pgtype.UUID
	// Immutable submitted resume version. Active profile resume changes do not alter historical applications.
	ResumeID  pgtype.UUID
	Status    string
	Message   pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type JobhubApplicationStatusEvent struct {
	ID             pgtype.UUID
	ApplicationID  pgtype.UUID
	ActorUserID    pgtype.UUID
	PreviousStatus pgtype.Text
	NewStatus      string
	CreatedAt      pgtype.Timestamptz
}

type JobhubCandidateLanguage struct {
	ID                 pgtype.UUID
	CandidateID        pgtype.UUID
	Language           string
	NormalizedLanguage string
	Proficiency        string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

// Private professional profiles accessed only through the authorized Go API.
type JobhubCandidateProfile struct {
	UserID                   pgtype.UUID
	PhotoUrl                 pgtype.Text
	City                     pgtype.Text
	BirthYear                pgtype.Int4
	Phone                    pgtype.Text
	About                    pgtype.Text
	CurrentPosition          pgtype.Text
	DesiredPosition          pgtype.Text
	YearsExperience          pgtype.Numeric
	ExperienceLevel          pgtype.Text
	Certifications           []string
	DesiredSalary            pgtype.Numeric
	Currency                 pgtype.Text
	SalaryPeriod             pgtype.Text
	PreferredLocations       []string
	PreferredEmploymentTypes []string
	PreferredWorkModes       []string
	PreferredCategories      []string
	PreferredRoles           []string
	SearchStatus             string
	GithubUrl                pgtype.Text
	LinkedinUrl              pgtype.Text
	PortfolioUrl             pgtype.Text
	WebsiteUrl               pgtype.Text
	AllowEmployerContact     bool
	ShowProfileToEmployers   bool
	ShowSalaryExpectations   bool
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	// Optional private full birth date. Legacy birth_year remains unchanged until the candidate explicitly supplies a date.
	BirthDate pgtype.Date
	// Canonical professional profile city, separate from search preference.
	CanonicalCityID pgtype.Text
	// Canonical preferred job-search cities.
	PreferredCityIds []string
}

type JobhubCandidateSkill struct {
	CandidateID pgtype.UUID
	SkillID     pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

type JobhubCompany struct {
	ID          pgtype.UUID
	Name        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Status      string
	IsVerified  bool
	Description pgtype.Text
	WebsiteUrl  pgtype.Text
	// HTTPS or application-local URL used for the public company profile logo.
	LogoUrl  pgtype.Text
	Industry pgtype.Text
	City     pgtype.Text
}

type JobhubCompanyFollow struct {
	CandidateID pgtype.UUID
	CompanyID   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

type JobhubCompanyMembership struct {
	ID        pgtype.UUID
	CompanyID pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type JobhubCompanySource struct {
	ID           pgtype.UUID
	CompanyID    pgtype.UUID
	Source       string
	ExternalID   string
	SourceName   pgtype.Text
	SourceUrl    pgtype.Text
	FirstSeenAt  pgtype.Timestamptz
	LastSeenAt   pgtype.Timestamptz
	LastSyncedAt pgtype.Timestamptz
}

type JobhubEducation struct {
	ID             pgtype.UUID
	CandidateID    pgtype.UUID
	Institution    string
	Degree         string
	FieldOfStudy   string
	StartYear      int32
	GraduationYear pgtype.Int4
	Description    pgtype.Text
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

// Server-side provider import audit metadata. Never store provider credentials here.
type JobhubIngestionRun struct {
	ID              pgtype.UUID
	Source          string
	Status          string
	SearchCount     int32
	RequestCount    int32
	FetchedCount    int32
	NormalizedCount int32
	InsertedCount   int32
	UpdatedCount    int32
	SkippedCount    int32
	ErrorCode       pgtype.Text
	ErrorMessage    pgtype.Text
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
}

type JobhubJob struct {
	ID                  pgtype.UUID
	Source              string
	ExternalID          pgtype.Text
	SourceUrl           pgtype.Text
	UpstreamSourceName  pgtype.Text
	CompanyID           pgtype.UUID
	CompanySourceID     pgtype.UUID
	CompanyNameRaw      pgtype.Text
	Title               string
	LocationRaw         pgtype.Text
	Description         pgtype.Text
	DescriptionKind     string
	EmploymentTypeRaw   pgtype.Text
	SalaryRaw           pgtype.Text
	SalaryMin           pgtype.Numeric
	SalaryMax           pgtype.Numeric
	SalaryCurrency      pgtype.Text
	SalaryPeriod        pgtype.Text
	SalaryGross         pgtype.Bool
	SalaryIsEstimated   pgtype.Bool
	ApplicationMethod   string
	ApplyUrl            pgtype.Text
	SourceStatus        string
	PublicationStatus   pgtype.Text
	FirstSeenAt         pgtype.Timestamptz
	LastSeenAt          pgtype.Timestamptz
	LastSyncedAt        pgtype.Timestamptz
	FreshUntil          pgtype.Timestamptz
	ExternalCreatedAt   pgtype.Timestamptz
	ExternalPublishedAt pgtype.Timestamptz
	ExternalUpdatedAt   pgtype.Timestamptz
	ExternalUpdatedRaw  pgtype.Text
	ExternalExpiresAt   pgtype.Timestamptz
	ExternalArchivedAt  pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Category            pgtype.Text
	Responsibilities    pgtype.Text
	Requirements        pgtype.Text
	NiceToHave          pgtype.Text
	Skills              []string
	WorkMode            pgtype.Text
	EmploymentType      pgtype.Text
	ExperienceLevel     pgtype.Text
	Benefits            []string
	SalaryVisible       bool
	ExpiresAt           pgtype.Timestamptz
	PublishedAt         pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
	ModerationStatus    string
	CreatedByUserID     pgtype.UUID
	// Canonical Kazakhstan city identifier; provider location_raw remains unchanged.
	CanonicalCityID pgtype.Text
}

type JobhubJobSource struct {
	Source      string
	Provider    string
	Market      pgtype.Text
	DisplayName string
	Enabled     bool
	// Must remain false until API-specific storage, redistribution, retention, attribution, and removal permissions are confirmed.
	ProductionPermissionsConfirmed bool
	AttributionText                pgtype.Text
	CreatedAt                      pgtype.Timestamptz
	UpdatedAt                      pgtype.Timestamptz
}

type JobhubResume struct {
	ID          pgtype.UUID
	CandidateID pgtype.UUID
	// Opaque server-side storage key. Never expose it in API responses.
	StorageKey       string
	OriginalFilename string
	ContentType      string
	SizeBytes        int64
	Status           string
	UploadedAt       pgtype.Timestamptz
	RetiredAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type JobhubSavedJob struct {
	CandidateID pgtype.UUID
	JobID       pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

// Stores only hashed opaque session and CSRF tokens. Raw tokens are never persisted.
type JobhubSession struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash []byte
	CsrfHash  []byte
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type JobhubSkill struct {
	ID             pgtype.UUID
	Name           string
	NormalizedName string
	CreatedAt      pgtype.Timestamptz
}

type JobhubUser struct {
	ID              pgtype.UUID
	FullName        string
	Email           string
	NormalizedEmail string
	PasswordHash    string
	Role            string
	Status          string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type JobhubWorkExperience struct {
	ID             pgtype.UUID
	CandidateID    pgtype.UUID
	Company        string
	Position       string
	EmploymentType string
	StartDate      pgtype.Date
	EndDate        pgtype.Date
	IsCurrent      bool
	Description    pgtype.Text
	Achievements   pgtype.Text
	Skills         []string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
