// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	DatabaseTime(ctx context.Context) (pgtype.Timestamptz, error)
}

var _ Querier = (*Queries)(nil)
